services:
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    image: scvmbot-bot:${IMAGE_TAG:-latest}
    container_name: scvmbot-bot
    restart: unless-stopped

    environment:
      - Discord__Token=${DISCORD_TOKEN}

    networks:
      - scvmbot-network

networks:
  scvmbot-network:
    driver: bridge
