title: ScvmBot
description: A Discord bot for tabletop RPG character generation
url: "https://chrismartin86.github.io"
baseurl: "/ScvmBot"

markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
